name: OpenAI smoke test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify OPENAI_API_KEY is available
        run: |
          if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "❌ OPENAI_API_KEY manquante dans ce repo."
            exit 1
          else
            echo "✅ OPENAI_API_KEY est présente (ok)."
          fi